version: 2
jobs:
    build:
        working_directory: ~/blog.stormcat.io
            machine: true
            steps:
                - checkout
                - run:
                    name: install hugo
                    command: go get -v github.com/gohugoio/hugo 
                - run:
                    name: install pygments
                    command: pip install pygments
                - run:
                    name: build hugo
                    pwd: blog/
                    command: hugo -t casper
